#[doc = "Register `BCR` reader"]
pub type R = crate::R<BcrSpec>;
#[doc = "Register `BCR` writer"]
pub type W = crate::W<BcrSpec>;
#[doc = "CAN Clock Source Selection\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Cclks {
    #[doc = "0: PCLK (generated by the PLL clock)"]
    _0 = 0,
    #[doc = "1: CANMCLK (generated by the main clock)"]
    _1 = 1,
}
impl From<Cclks> for bool {
    #[inline(always)]
    fn from(variant: Cclks) -> Self {
        variant as u8 != 0
    }
}
#[doc = "Field `CCLKS` reader - CAN Clock Source Selection"]
pub type CclksR = crate::BitReader<Cclks>;
impl CclksR {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub const fn variant(&self) -> Cclks {
        match self.bits {
            false => Cclks::_0,
            true => Cclks::_1,
        }
    }
    #[doc = "PCLK (generated by the PLL clock)"]
    #[inline(always)]
    pub fn is_0(&self) -> bool {
        *self == Cclks::_0
    }
    #[doc = "CANMCLK (generated by the main clock)"]
    #[inline(always)]
    pub fn is_1(&self) -> bool {
        *self == Cclks::_1
    }
}
#[doc = "Field `CCLKS` writer - CAN Clock Source Selection"]
pub type CclksW<'a, REG> = crate::BitWriter<'a, REG, Cclks>;
impl<'a, REG> CclksW<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    #[doc = "PCLK (generated by the PLL clock)"]
    #[inline(always)]
    pub fn _0(self) -> &'a mut crate::W<REG> {
        self.variant(Cclks::_0)
    }
    #[doc = "CANMCLK (generated by the main clock)"]
    #[inline(always)]
    pub fn _1(self) -> &'a mut crate::W<REG> {
        self.variant(Cclks::_1)
    }
}
#[doc = "Time Segment 2 Control\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Tseg2 {
    #[doc = "0: Setting prohibited"]
    _000 = 0,
    #[doc = "1: 2 Tq"]
    _001 = 1,
    #[doc = "2: 3 Tq"]
    _010 = 2,
    #[doc = "3: 4 Tq"]
    _011 = 3,
    #[doc = "4: 5 Tq"]
    _100 = 4,
    #[doc = "5: 6 Tq"]
    _101 = 5,
    #[doc = "6: 7 Tq"]
    _110 = 6,
    #[doc = "7: 8 Tq"]
    _111 = 7,
}
impl From<Tseg2> for u8 {
    #[inline(always)]
    fn from(variant: Tseg2) -> Self {
        variant as _
    }
}
impl crate::FieldSpec for Tseg2 {
    type Ux = u8;
}
impl crate::IsEnum for Tseg2 {}
#[doc = "Field `TSEG2` reader - Time Segment 2 Control"]
pub type Tseg2R = crate::FieldReader<Tseg2>;
impl Tseg2R {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub const fn variant(&self) -> Tseg2 {
        match self.bits {
            0 => Tseg2::_000,
            1 => Tseg2::_001,
            2 => Tseg2::_010,
            3 => Tseg2::_011,
            4 => Tseg2::_100,
            5 => Tseg2::_101,
            6 => Tseg2::_110,
            7 => Tseg2::_111,
            _ => unreachable!(),
        }
    }
    #[doc = "Setting prohibited"]
    #[inline(always)]
    pub fn is_000(&self) -> bool {
        *self == Tseg2::_000
    }
    #[doc = "2 Tq"]
    #[inline(always)]
    pub fn is_001(&self) -> bool {
        *self == Tseg2::_001
    }
    #[doc = "3 Tq"]
    #[inline(always)]
    pub fn is_010(&self) -> bool {
        *self == Tseg2::_010
    }
    #[doc = "4 Tq"]
    #[inline(always)]
    pub fn is_011(&self) -> bool {
        *self == Tseg2::_011
    }
    #[doc = "5 Tq"]
    #[inline(always)]
    pub fn is_100(&self) -> bool {
        *self == Tseg2::_100
    }
    #[doc = "6 Tq"]
    #[inline(always)]
    pub fn is_101(&self) -> bool {
        *self == Tseg2::_101
    }
    #[doc = "7 Tq"]
    #[inline(always)]
    pub fn is_110(&self) -> bool {
        *self == Tseg2::_110
    }
    #[doc = "8 Tq"]
    #[inline(always)]
    pub fn is_111(&self) -> bool {
        *self == Tseg2::_111
    }
}
#[doc = "Field `TSEG2` writer - Time Segment 2 Control"]
pub type Tseg2W<'a, REG> = crate::FieldWriter<'a, REG, 3, Tseg2, crate::Safe>;
impl<'a, REG> Tseg2W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
    REG::Ux: From<u8>,
{
    #[doc = "Setting prohibited"]
    #[inline(always)]
    pub fn _000(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg2::_000)
    }
    #[doc = "2 Tq"]
    #[inline(always)]
    pub fn _001(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg2::_001)
    }
    #[doc = "3 Tq"]
    #[inline(always)]
    pub fn _010(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg2::_010)
    }
    #[doc = "4 Tq"]
    #[inline(always)]
    pub fn _011(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg2::_011)
    }
    #[doc = "5 Tq"]
    #[inline(always)]
    pub fn _100(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg2::_100)
    }
    #[doc = "6 Tq"]
    #[inline(always)]
    pub fn _101(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg2::_101)
    }
    #[doc = "7 Tq"]
    #[inline(always)]
    pub fn _110(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg2::_110)
    }
    #[doc = "8 Tq"]
    #[inline(always)]
    pub fn _111(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg2::_111)
    }
}
#[doc = "Resynchronization Jump Width Control\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Sjw {
    #[doc = "0: 1 Tq"]
    _00 = 0,
    #[doc = "1: 2 Tq"]
    _01 = 1,
    #[doc = "2: 3 Tq"]
    _10 = 2,
    #[doc = "3: 4 Tq"]
    _11 = 3,
}
impl From<Sjw> for u8 {
    #[inline(always)]
    fn from(variant: Sjw) -> Self {
        variant as _
    }
}
impl crate::FieldSpec for Sjw {
    type Ux = u8;
}
impl crate::IsEnum for Sjw {}
#[doc = "Field `SJW` reader - Resynchronization Jump Width Control"]
pub type SjwR = crate::FieldReader<Sjw>;
impl SjwR {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub const fn variant(&self) -> Sjw {
        match self.bits {
            0 => Sjw::_00,
            1 => Sjw::_01,
            2 => Sjw::_10,
            3 => Sjw::_11,
            _ => unreachable!(),
        }
    }
    #[doc = "1 Tq"]
    #[inline(always)]
    pub fn is_00(&self) -> bool {
        *self == Sjw::_00
    }
    #[doc = "2 Tq"]
    #[inline(always)]
    pub fn is_01(&self) -> bool {
        *self == Sjw::_01
    }
    #[doc = "3 Tq"]
    #[inline(always)]
    pub fn is_10(&self) -> bool {
        *self == Sjw::_10
    }
    #[doc = "4 Tq"]
    #[inline(always)]
    pub fn is_11(&self) -> bool {
        *self == Sjw::_11
    }
}
#[doc = "Field `SJW` writer - Resynchronization Jump Width Control"]
pub type SjwW<'a, REG> = crate::FieldWriter<'a, REG, 2, Sjw, crate::Safe>;
impl<'a, REG> SjwW<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
    REG::Ux: From<u8>,
{
    #[doc = "1 Tq"]
    #[inline(always)]
    pub fn _00(self) -> &'a mut crate::W<REG> {
        self.variant(Sjw::_00)
    }
    #[doc = "2 Tq"]
    #[inline(always)]
    pub fn _01(self) -> &'a mut crate::W<REG> {
        self.variant(Sjw::_01)
    }
    #[doc = "3 Tq"]
    #[inline(always)]
    pub fn _10(self) -> &'a mut crate::W<REG> {
        self.variant(Sjw::_10)
    }
    #[doc = "4 Tq"]
    #[inline(always)]
    pub fn _11(self) -> &'a mut crate::W<REG> {
        self.variant(Sjw::_11)
    }
}
#[doc = "Field `BRP` reader - Prescaler Division Ratio Select . These bits set the frequency of the CAN communication clock (fCANCLK)."]
pub type BrpR = crate::FieldReader<u16>;
#[doc = "Field `BRP` writer - Prescaler Division Ratio Select . These bits set the frequency of the CAN communication clock (fCANCLK)."]
pub type BrpW<'a, REG> = crate::FieldWriter<'a, REG, 10, u16>;
#[doc = "Time Segment 1 Control\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Tseg1 {
    #[doc = "3: 4 Tq"]
    _0011 = 3,
    #[doc = "4: 5 Tq"]
    _0100 = 4,
    #[doc = "5: 6 Tq"]
    _0101 = 5,
    #[doc = "6: 7 Tq"]
    _0110 = 6,
    #[doc = "7: 8 Tq"]
    _0111 = 7,
    #[doc = "8: 9 Tq"]
    _1000 = 8,
    #[doc = "9: 10 Tq"]
    _1001 = 9,
    #[doc = "10: 11 Tq"]
    _1010 = 10,
    #[doc = "11: 12 Tq"]
    _1011 = 11,
    #[doc = "12: 13 Tq"]
    _1100 = 12,
    #[doc = "13: 14 Tq"]
    _1101 = 13,
    #[doc = "14: 15 Tq"]
    _1110 = 14,
    #[doc = "15: 16 Tq"]
    _1111 = 15,
    #[doc = "0: Setting prohibited"]
    Others = 0,
}
impl From<Tseg1> for u8 {
    #[inline(always)]
    fn from(variant: Tseg1) -> Self {
        variant as _
    }
}
impl crate::FieldSpec for Tseg1 {
    type Ux = u8;
}
impl crate::IsEnum for Tseg1 {}
#[doc = "Field `TSEG1` reader - Time Segment 1 Control"]
pub type Tseg1R = crate::FieldReader<Tseg1>;
impl Tseg1R {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub const fn variant(&self) -> Tseg1 {
        match self.bits {
            3 => Tseg1::_0011,
            4 => Tseg1::_0100,
            5 => Tseg1::_0101,
            6 => Tseg1::_0110,
            7 => Tseg1::_0111,
            8 => Tseg1::_1000,
            9 => Tseg1::_1001,
            10 => Tseg1::_1010,
            11 => Tseg1::_1011,
            12 => Tseg1::_1100,
            13 => Tseg1::_1101,
            14 => Tseg1::_1110,
            15 => Tseg1::_1111,
            _ => Tseg1::Others,
        }
    }
    #[doc = "4 Tq"]
    #[inline(always)]
    pub fn is_0011(&self) -> bool {
        *self == Tseg1::_0011
    }
    #[doc = "5 Tq"]
    #[inline(always)]
    pub fn is_0100(&self) -> bool {
        *self == Tseg1::_0100
    }
    #[doc = "6 Tq"]
    #[inline(always)]
    pub fn is_0101(&self) -> bool {
        *self == Tseg1::_0101
    }
    #[doc = "7 Tq"]
    #[inline(always)]
    pub fn is_0110(&self) -> bool {
        *self == Tseg1::_0110
    }
    #[doc = "8 Tq"]
    #[inline(always)]
    pub fn is_0111(&self) -> bool {
        *self == Tseg1::_0111
    }
    #[doc = "9 Tq"]
    #[inline(always)]
    pub fn is_1000(&self) -> bool {
        *self == Tseg1::_1000
    }
    #[doc = "10 Tq"]
    #[inline(always)]
    pub fn is_1001(&self) -> bool {
        *self == Tseg1::_1001
    }
    #[doc = "11 Tq"]
    #[inline(always)]
    pub fn is_1010(&self) -> bool {
        *self == Tseg1::_1010
    }
    #[doc = "12 Tq"]
    #[inline(always)]
    pub fn is_1011(&self) -> bool {
        *self == Tseg1::_1011
    }
    #[doc = "13 Tq"]
    #[inline(always)]
    pub fn is_1100(&self) -> bool {
        *self == Tseg1::_1100
    }
    #[doc = "14 Tq"]
    #[inline(always)]
    pub fn is_1101(&self) -> bool {
        *self == Tseg1::_1101
    }
    #[doc = "15 Tq"]
    #[inline(always)]
    pub fn is_1110(&self) -> bool {
        *self == Tseg1::_1110
    }
    #[doc = "16 Tq"]
    #[inline(always)]
    pub fn is_1111(&self) -> bool {
        *self == Tseg1::_1111
    }
    #[doc = "Setting prohibited"]
    #[inline(always)]
    pub fn is_others(&self) -> bool {
        matches!(self.variant(), Tseg1::Others)
    }
}
#[doc = "Field `TSEG1` writer - Time Segment 1 Control"]
pub type Tseg1W<'a, REG> = crate::FieldWriter<'a, REG, 4, Tseg1, crate::Safe>;
impl<'a, REG> Tseg1W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
    REG::Ux: From<u8>,
{
    #[doc = "4 Tq"]
    #[inline(always)]
    pub fn _0011(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_0011)
    }
    #[doc = "5 Tq"]
    #[inline(always)]
    pub fn _0100(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_0100)
    }
    #[doc = "6 Tq"]
    #[inline(always)]
    pub fn _0101(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_0101)
    }
    #[doc = "7 Tq"]
    #[inline(always)]
    pub fn _0110(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_0110)
    }
    #[doc = "8 Tq"]
    #[inline(always)]
    pub fn _0111(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_0111)
    }
    #[doc = "9 Tq"]
    #[inline(always)]
    pub fn _1000(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_1000)
    }
    #[doc = "10 Tq"]
    #[inline(always)]
    pub fn _1001(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_1001)
    }
    #[doc = "11 Tq"]
    #[inline(always)]
    pub fn _1010(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_1010)
    }
    #[doc = "12 Tq"]
    #[inline(always)]
    pub fn _1011(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_1011)
    }
    #[doc = "13 Tq"]
    #[inline(always)]
    pub fn _1100(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_1100)
    }
    #[doc = "14 Tq"]
    #[inline(always)]
    pub fn _1101(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_1101)
    }
    #[doc = "15 Tq"]
    #[inline(always)]
    pub fn _1110(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_1110)
    }
    #[doc = "16 Tq"]
    #[inline(always)]
    pub fn _1111(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::_1111)
    }
    #[doc = "Setting prohibited"]
    #[inline(always)]
    pub fn others(self) -> &'a mut crate::W<REG> {
        self.variant(Tseg1::Others)
    }
}
impl R {
    #[doc = "Bit 0 - CAN Clock Source Selection"]
    #[inline(always)]
    pub fn cclks(&self) -> CclksR {
        CclksR::new((self.bits & 1) != 0)
    }
    #[doc = "Bits 8:10 - Time Segment 2 Control"]
    #[inline(always)]
    pub fn tseg2(&self) -> Tseg2R {
        Tseg2R::new(((self.bits >> 8) & 7) as u8)
    }
    #[doc = "Bits 12:13 - Resynchronization Jump Width Control"]
    #[inline(always)]
    pub fn sjw(&self) -> SjwR {
        SjwR::new(((self.bits >> 12) & 3) as u8)
    }
    #[doc = "Bits 16:25 - Prescaler Division Ratio Select . These bits set the frequency of the CAN communication clock (fCANCLK)."]
    #[inline(always)]
    pub fn brp(&self) -> BrpR {
        BrpR::new(((self.bits >> 16) & 0x03ff) as u16)
    }
    #[doc = "Bits 28:31 - Time Segment 1 Control"]
    #[inline(always)]
    pub fn tseg1(&self) -> Tseg1R {
        Tseg1R::new(((self.bits >> 28) & 0x0f) as u8)
    }
}
impl W {
    #[doc = "Bit 0 - CAN Clock Source Selection"]
    #[inline(always)]
    pub fn cclks(&mut self) -> CclksW<'_, BcrSpec> {
        CclksW::new(self, 0)
    }
    #[doc = "Bits 8:10 - Time Segment 2 Control"]
    #[inline(always)]
    pub fn tseg2(&mut self) -> Tseg2W<'_, BcrSpec> {
        Tseg2W::new(self, 8)
    }
    #[doc = "Bits 12:13 - Resynchronization Jump Width Control"]
    #[inline(always)]
    pub fn sjw(&mut self) -> SjwW<'_, BcrSpec> {
        SjwW::new(self, 12)
    }
    #[doc = "Bits 16:25 - Prescaler Division Ratio Select . These bits set the frequency of the CAN communication clock (fCANCLK)."]
    #[inline(always)]
    pub fn brp(&mut self) -> BrpW<'_, BcrSpec> {
        BrpW::new(self, 16)
    }
    #[doc = "Bits 28:31 - Time Segment 1 Control"]
    #[inline(always)]
    pub fn tseg1(&mut self) -> Tseg1W<'_, BcrSpec> {
        Tseg1W::new(self, 28)
    }
}
#[doc = "Bit Configuration Register\n\nYou can [`read`](crate::Reg::read) this register and get [`bcr::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`bcr::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct BcrSpec;
impl crate::RegisterSpec for BcrSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`bcr::R`](R) reader structure"]
impl crate::Readable for BcrSpec {}
#[doc = "`write(|w| ..)` method takes [`bcr::W`](W) writer structure"]
impl crate::Writable for BcrSpec {
    type Safety = crate::Unsafe;
}
#[doc = "`reset()` method sets BCR to value 0"]
impl crate::Resettable for BcrSpec {}
