#![doc = "Peripheral access API for R7FA4M1AB microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn IEL0();
    fn IEL1();
    fn IEL2();
    fn IEL3();
    fn IEL4();
    fn IEL5();
    fn IEL6();
    fn IEL7();
    fn IEL8();
    fn IEL9();
    fn IEL10();
    fn IEL11();
    fn IEL12();
    fn IEL13();
    fn IEL14();
    fn IEL15();
    fn IEL16();
    fn IEL17();
    fn IEL18();
    fn IEL19();
    fn IEL20();
    fn IEL21();
    fn IEL22();
    fn IEL23();
    fn IEL24();
    fn IEL25();
    fn IEL26();
    fn IEL27();
    fn IEL28();
    fn IEL29();
    fn IEL30();
    fn IEL31();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 32] = [
    Vector { _handler: IEL0 },
    Vector { _handler: IEL1 },
    Vector { _handler: IEL2 },
    Vector { _handler: IEL3 },
    Vector { _handler: IEL4 },
    Vector { _handler: IEL5 },
    Vector { _handler: IEL6 },
    Vector { _handler: IEL7 },
    Vector { _handler: IEL8 },
    Vector { _handler: IEL9 },
    Vector { _handler: IEL10 },
    Vector { _handler: IEL11 },
    Vector { _handler: IEL12 },
    Vector { _handler: IEL13 },
    Vector { _handler: IEL14 },
    Vector { _handler: IEL15 },
    Vector { _handler: IEL16 },
    Vector { _handler: IEL17 },
    Vector { _handler: IEL18 },
    Vector { _handler: IEL19 },
    Vector { _handler: IEL20 },
    Vector { _handler: IEL21 },
    Vector { _handler: IEL22 },
    Vector { _handler: IEL23 },
    Vector { _handler: IEL24 },
    Vector { _handler: IEL25 },
    Vector { _handler: IEL26 },
    Vector { _handler: IEL27 },
    Vector { _handler: IEL28 },
    Vector { _handler: IEL29 },
    Vector { _handler: IEL30 },
    Vector { _handler: IEL31 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - ICU Interrupt 0"]
    IEL0 = 0,
    #[doc = "1 - ICU Interrupt 1"]
    IEL1 = 1,
    #[doc = "2 - ICU Interrupt 2"]
    IEL2 = 2,
    #[doc = "3 - ICU Interrupt 3"]
    IEL3 = 3,
    #[doc = "4 - ICU Interrupt 4"]
    IEL4 = 4,
    #[doc = "5 - ICU Interrupt 5"]
    IEL5 = 5,
    #[doc = "6 - ICU Interrupt 6"]
    IEL6 = 6,
    #[doc = "7 - ICU Interrupt 7"]
    IEL7 = 7,
    #[doc = "8 - ICU Interrupt 8"]
    IEL8 = 8,
    #[doc = "9 - ICU Interrupt 9"]
    IEL9 = 9,
    #[doc = "10 - ICU Interrupt 10"]
    IEL10 = 10,
    #[doc = "11 - ICU Interrupt 11"]
    IEL11 = 11,
    #[doc = "12 - ICU Interrupt 12"]
    IEL12 = 12,
    #[doc = "13 - ICU Interrupt 13"]
    IEL13 = 13,
    #[doc = "14 - ICU Interrupt 14"]
    IEL14 = 14,
    #[doc = "15 - ICU Interrupt 15"]
    IEL15 = 15,
    #[doc = "16 - ICU Interrupt 16"]
    IEL16 = 16,
    #[doc = "17 - ICU Interrupt 17"]
    IEL17 = 17,
    #[doc = "18 - ICU Interrupt 18"]
    IEL18 = 18,
    #[doc = "19 - ICU Interrupt 19"]
    IEL19 = 19,
    #[doc = "20 - ICU Interrupt 20"]
    IEL20 = 20,
    #[doc = "21 - ICU Interrupt 21"]
    IEL21 = 21,
    #[doc = "22 - ICU Interrupt 22"]
    IEL22 = 22,
    #[doc = "23 - ICU Interrupt 23"]
    IEL23 = 23,
    #[doc = "24 - ICU Interrupt 24"]
    IEL24 = 24,
    #[doc = "25 - ICU Interrupt 25"]
    IEL25 = 25,
    #[doc = "26 - ICU Interrupt 26"]
    IEL26 = 26,
    #[doc = "27 - ICU Interrupt 27"]
    IEL27 = 27,
    #[doc = "28 - ICU Interrupt 28"]
    IEL28 = 28,
    #[doc = "29 - ICU Interrupt 29"]
    IEL29 = 29,
    #[doc = "30 - ICU Interrupt 30"]
    IEL30 = 30,
    #[doc = "31 - ICU Interrupt 31"]
    IEL31 = 31,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "System Control"]
pub type System = crate::Periph<system::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for System {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("System").finish()
    }
}
#[doc = "System Control"]
pub mod system;
#[doc = "BUS Control"]
pub type Bus = crate::Periph<bus::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Bus {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bus").finish()
    }
}
#[doc = "BUS Control"]
pub mod bus;
#[doc = "Clock Frequency Accuracy Measurement Circuit"]
pub type Cac = crate::Periph<cac::RegisterBlock, 0x4004_4600>;
impl core::fmt::Debug for Cac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cac").finish()
    }
}
#[doc = "Clock Frequency Accuracy Measurement Circuit"]
pub mod cac;
#[doc = "CAN0 Module"]
pub type Can0 = crate::Periph<can0::RegisterBlock, 0x4005_0000>;
impl core::fmt::Debug for Can0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Can0").finish()
    }
}
#[doc = "CAN0 Module"]
pub mod can0;
#[doc = "Debug Function"]
pub type Dbg = crate::Periph<dbg::RegisterBlock, 0x4001_b000>;
impl core::fmt::Debug for Dbg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dbg").finish()
    }
}
#[doc = "Debug Function"]
pub mod dbg;
#[doc = "CRC Calculator"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4007_4000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "CRC Calculator"]
pub mod crc;
#[doc = "Capacitive Touch Sensing Unit"]
pub type Ctsu = crate::Periph<ctsu::RegisterBlock, 0x4008_1000>;
impl core::fmt::Debug for Ctsu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctsu").finish()
    }
}
#[doc = "Capacitive Touch Sensing Unit"]
pub mod ctsu;
#[doc = "12-bit D/A converter"]
pub type Dac12 = crate::Periph<dac12::RegisterBlock, 0x4005_e000>;
impl core::fmt::Debug for Dac12 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac12").finish()
    }
}
#[doc = "12-bit D/A converter"]
pub mod dac12;
#[doc = "8-bit D/A converter"]
pub type Dac8 = crate::Periph<dac8::RegisterBlock, 0x4009_e000>;
impl core::fmt::Debug for Dac8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac8").finish()
    }
}
#[doc = "8-bit D/A converter"]
pub mod dac8;
#[doc = "Direct memory access controller 0"]
pub type Dmac0 = crate::Periph<dmac0::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Dmac0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac0").finish()
    }
}
#[doc = "Direct memory access controller 0"]
pub mod dmac0;
#[doc = "Direct memory access controller 1"]
pub type Dmac1 = crate::Periph<dmac0::RegisterBlock, 0x4000_5040>;
impl core::fmt::Debug for Dmac1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac1").finish()
    }
}
#[doc = "Direct memory access controller 1"]
pub use self::dmac0 as dmac1;
#[doc = "Direct memory access controller 2"]
pub type Dmac2 = crate::Periph<dmac0::RegisterBlock, 0x4000_5080>;
impl core::fmt::Debug for Dmac2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac2").finish()
    }
}
#[doc = "Direct memory access controller 2"]
pub use self::dmac0 as dmac2;
#[doc = "Direct memory access controller 3"]
pub type Dmac3 = crate::Periph<dmac0::RegisterBlock, 0x4000_50c0>;
impl core::fmt::Debug for Dmac3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac3").finish()
    }
}
#[doc = "Direct memory access controller 3"]
pub use self::dmac0 as dmac3;
#[doc = "DMAC Module Activation"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4000_5200>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "DMAC Module Activation"]
pub mod dma;
#[doc = "Data Operation Circuit"]
pub type Doc = crate::Periph<doc::RegisterBlock, 0x4005_4100>;
impl core::fmt::Debug for Doc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Doc").finish()
    }
}
#[doc = "Data Operation Circuit"]
pub mod doc;
#[doc = "Data Transfer Controller"]
pub type Dtc = crate::Periph<dtc::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for Dtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dtc").finish()
    }
}
#[doc = "Data Transfer Controller"]
pub mod dtc;
#[doc = "Event Link Controller"]
pub type Elc = crate::Periph<elc::RegisterBlock, 0x4004_1000>;
impl core::fmt::Debug for Elc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Elc").finish()
    }
}
#[doc = "Event Link Controller"]
pub mod elc;
#[doc = "Flash Cache"]
pub type Fcache = crate::Periph<fcache::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Fcache {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fcache").finish()
    }
}
#[doc = "Flash Cache"]
pub mod fcache;
#[doc = "Port 0 Control Registers"]
pub type Port0 = crate::Periph<port0::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for Port0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port0").finish()
    }
}
#[doc = "Port 0 Control Registers"]
pub mod port0;
#[doc = "Port 1 Control Registers"]
pub type Port1 = crate::Periph<port1::RegisterBlock, 0x4004_0020>;
impl core::fmt::Debug for Port1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port1").finish()
    }
}
#[doc = "Port 1 Control Registers"]
pub mod port1;
#[doc = "Port 2 Control Registers"]
pub type Port2 = crate::Periph<port1::RegisterBlock, 0x4004_0040>;
impl core::fmt::Debug for Port2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port2").finish()
    }
}
#[doc = "Port 2 Control Registers"]
pub use self::port1 as port2;
#[doc = "Port 3 Control Registers"]
pub type Port3 = crate::Periph<port1::RegisterBlock, 0x4004_0060>;
impl core::fmt::Debug for Port3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port3").finish()
    }
}
#[doc = "Port 3 Control Registers"]
pub use self::port1 as port3;
#[doc = "Port 4 Control Registers"]
pub type Port4 = crate::Periph<port1::RegisterBlock, 0x4004_0080>;
impl core::fmt::Debug for Port4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port4").finish()
    }
}
#[doc = "Port 4 Control Registers"]
pub use self::port1 as port4;
#[doc = "Port 5 Control Registers"]
pub type Port5 = crate::Periph<port0::RegisterBlock, 0x4004_00a0>;
impl core::fmt::Debug for Port5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port5").finish()
    }
}
#[doc = "Port 5 Control Registers"]
pub use self::port0 as port5;
#[doc = "Port 6 Control Registers"]
pub type Port6 = crate::Periph<port0::RegisterBlock, 0x4004_00c0>;
impl core::fmt::Debug for Port6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port6").finish()
    }
}
#[doc = "Port 6 Control Registers"]
pub use self::port0 as port6;
#[doc = "Port 7 Control Registers"]
pub type Port7 = crate::Periph<port0::RegisterBlock, 0x4004_00e0>;
impl core::fmt::Debug for Port7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port7").finish()
    }
}
#[doc = "Port 7 Control Registers"]
pub use self::port0 as port7;
#[doc = "Port 8 Control Registers"]
pub type Port8 = crate::Periph<port0::RegisterBlock, 0x4004_0100>;
impl core::fmt::Debug for Port8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port8").finish()
    }
}
#[doc = "Port 8 Control Registers"]
pub use self::port0 as port8;
#[doc = "Port 9 Control Registers"]
pub type Port9 = crate::Periph<port0::RegisterBlock, 0x4004_0120>;
impl core::fmt::Debug for Port9 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port9").finish()
    }
}
#[doc = "Port 9 Control Registers"]
pub use self::port0 as port9;
#[doc = "Pmn Pin Function Control Register"]
pub type Pfs = crate::Periph<pfs::RegisterBlock, 0x4004_0800>;
impl core::fmt::Debug for Pfs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pfs").finish()
    }
}
#[doc = "Pmn Pin Function Control Register"]
pub mod pfs;
#[doc = "Miscellaneous Port Control Register"]
pub type Pmisc = crate::Periph<pmisc::RegisterBlock, 0x4004_0d00>;
impl core::fmt::Debug for Pmisc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pmisc").finish()
    }
}
#[doc = "Miscellaneous Port Control Register"]
pub mod pmisc;
#[doc = "Interrupt Controller"]
pub type Icu = crate::Periph<icu::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Icu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Icu").finish()
    }
}
#[doc = "Interrupt Controller"]
pub mod icu;
#[doc = "Inter-Integrated Circuit 0"]
pub type Iic0 = crate::Periph<iic0::RegisterBlock, 0x4005_3000>;
impl core::fmt::Debug for Iic0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iic0").finish()
    }
}
#[doc = "Inter-Integrated Circuit 0"]
pub mod iic0;
#[doc = "Inter-Integrated Circuit 1"]
pub type Iic1 = crate::Periph<iic1::RegisterBlock, 0x4005_3100>;
impl core::fmt::Debug for Iic1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iic1").finish()
    }
}
#[doc = "Inter-Integrated Circuit 1"]
pub mod iic1;
#[doc = "Independent Watchdog Timer"]
pub type Iwdt = crate::Periph<iwdt::RegisterBlock, 0x4004_4400>;
impl core::fmt::Debug for Iwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iwdt").finish()
    }
}
#[doc = "Independent Watchdog Timer"]
pub mod iwdt;
#[doc = "Key Interrupt Function"]
pub type Kint = crate::Periph<kint::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for Kint {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Kint").finish()
    }
}
#[doc = "Key Interrupt Function"]
pub mod kint;
#[doc = "Module Stop Control B,C,D"]
pub type Mstp = crate::Periph<mstp::RegisterBlock, 0x4004_7000>;
impl core::fmt::Debug for Mstp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mstp").finish()
    }
}
#[doc = "Module Stop Control B,C,D"]
pub mod mstp;
#[doc = "Bus Master MPU"]
pub type Mmpu = crate::Periph<mmpu::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Mmpu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mmpu").finish()
    }
}
#[doc = "Bus Master MPU"]
pub mod mmpu;
#[doc = "Bus Slave MPU"]
pub type Smpu = crate::Periph<smpu::RegisterBlock, 0x4000_0c00>;
impl core::fmt::Debug for Smpu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Smpu").finish()
    }
}
#[doc = "Bus Slave MPU"]
pub mod smpu;
#[doc = "CPU Stack Pointer Monitor"]
pub type Spmon = crate::Periph<spmon::RegisterBlock, 0x4000_0d00>;
impl core::fmt::Debug for Spmon {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spmon").finish()
    }
}
#[doc = "CPU Stack Pointer Monitor"]
pub mod spmon;
#[doc = "OperationalAmplifier"]
pub type Opamp = crate::Periph<opamp::RegisterBlock, 0x4008_6000>;
impl core::fmt::Debug for Opamp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Opamp").finish()
    }
}
#[doc = "OperationalAmplifier"]
pub mod opamp;
#[doc = "Port Output Enable Module for GPT"]
pub type Poeg = crate::Periph<poeg::RegisterBlock, 0x4004_2000>;
impl core::fmt::Debug for Poeg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Poeg").finish()
    }
}
#[doc = "Port Output Enable Module for GPT"]
pub mod poeg;
#[doc = "SRAM Control"]
pub type Sram = crate::Periph<sram::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Sram {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sram").finish()
    }
}
#[doc = "SRAM Control"]
pub mod sram;
#[doc = "Realtime Clock"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4004_4000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "Realtime Clock"]
pub mod rtc;
#[doc = "Serial Communication Interface 0"]
pub type Sci0 = crate::Periph<sci0::RegisterBlock, 0x4007_0000>;
impl core::fmt::Debug for Sci0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sci0").finish()
    }
}
#[doc = "Serial Communication Interface 0"]
pub mod sci0;
#[doc = "Serial Communication Interface 1"]
pub type Sci1 = crate::Periph<sci0::RegisterBlock, 0x4007_0020>;
impl core::fmt::Debug for Sci1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sci1").finish()
    }
}
#[doc = "Serial Communication Interface 1"]
pub use self::sci0 as sci1;
#[doc = "Serial Communication Interface 2"]
pub type Sci2 = crate::Periph<sci2::RegisterBlock, 0x4007_0040>;
impl core::fmt::Debug for Sci2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sci2").finish()
    }
}
#[doc = "Serial Communication Interface 2"]
pub mod sci2;
#[doc = "Serial Communication Interface 9"]
pub type Sci9 = crate::Periph<sci2::RegisterBlock, 0x4007_0120>;
impl core::fmt::Debug for Sci9 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sci9").finish()
    }
}
#[doc = "Serial Communication Interface 9"]
pub use self::sci2 as sci9;
#[doc = "Segment LCD Controller/Driver"]
pub type Slcdc = crate::Periph<slcdc::RegisterBlock, 0x4008_2000>;
impl core::fmt::Debug for Slcdc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Slcdc").finish()
    }
}
#[doc = "Segment LCD Controller/Driver"]
pub mod slcdc;
#[doc = "Serial Peripheral Interface 0"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4007_2000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "Serial Peripheral Interface 0"]
pub mod spi0;
#[doc = "Serial Peripheral Interface 1"]
pub type Spi1 = crate::Periph<spi1::RegisterBlock, 0x4007_2100>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "Serial Peripheral Interface 1"]
pub mod spi1;
#[doc = "Serial Sound Interface Ver.2.0"]
pub type Ssie0 = crate::Periph<ssie0::RegisterBlock, 0x4004_e000>;
impl core::fmt::Debug for Ssie0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ssie0").finish()
    }
}
#[doc = "Serial Sound Interface Ver.2.0"]
pub mod ssie0;
#[doc = "Temperature Sensor"]
pub type Tsn = crate::Periph<tsn::RegisterBlock, 0x407e_c000>;
impl core::fmt::Debug for Tsn {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tsn").finish()
    }
}
#[doc = "Temperature Sensor"]
pub mod tsn;
#[doc = "USB 2.0 FS Module"]
pub type Usbfs = crate::Periph<usbfs::RegisterBlock, 0x4009_0000>;
impl core::fmt::Debug for Usbfs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usbfs").finish()
    }
}
#[doc = "USB 2.0 FS Module"]
pub mod usbfs;
#[doc = "Watchdog Timer"]
pub type Wdt = crate::Periph<wdt::RegisterBlock, 0x4004_4200>;
impl core::fmt::Debug for Wdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt").finish()
    }
}
#[doc = "Watchdog Timer"]
pub mod wdt;
#[doc = "Low-Power Analog Comparator"]
pub type Acmplp = crate::Periph<acmplp::RegisterBlock, 0x4008_5e00>;
impl core::fmt::Debug for Acmplp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Acmplp").finish()
    }
}
#[doc = "Low-Power Analog Comparator"]
pub mod acmplp;
#[doc = "14bit A/D Converter"]
pub type Adc140 = crate::Periph<adc140::RegisterBlock, 0x4005_c000>;
impl core::fmt::Debug for Adc140 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc140").finish()
    }
}
#[doc = "14bit A/D Converter"]
pub mod adc140;
#[doc = "Asynchronous General purpose Timer 0"]
pub type Agt0 = crate::Periph<agt0::RegisterBlock, 0x4008_4000>;
impl core::fmt::Debug for Agt0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Agt0").finish()
    }
}
#[doc = "Asynchronous General purpose Timer 0"]
pub mod agt0;
#[doc = "Asynchronous General purpose Timer 1"]
pub type Agt1 = crate::Periph<agt0::RegisterBlock, 0x4008_4100>;
impl core::fmt::Debug for Agt1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Agt1").finish()
    }
}
#[doc = "Asynchronous General purpose Timer 1"]
pub use self::agt0 as agt1;
#[doc = "General PWM Timer 0 (32-bit)"]
pub type Gpt320 = crate::Periph<gpt320::RegisterBlock, 0x4007_8000>;
impl core::fmt::Debug for Gpt320 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpt320").finish()
    }
}
#[doc = "General PWM Timer 0 (32-bit)"]
pub mod gpt320;
#[doc = "General PWM Timer 1 (32-bit)"]
pub type Gpt321 = crate::Periph<gpt320::RegisterBlock, 0x4007_8100>;
impl core::fmt::Debug for Gpt321 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpt321").finish()
    }
}
#[doc = "General PWM Timer 1 (32-bit)"]
pub use self::gpt320 as gpt321;
#[doc = "General PWM Timer 2 (16-bit)"]
pub type Gpt162 = crate::Periph<gpt162::RegisterBlock, 0x4007_8200>;
impl core::fmt::Debug for Gpt162 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpt162").finish()
    }
}
#[doc = "General PWM Timer 2 (16-bit)"]
pub mod gpt162;
#[doc = "General PWM Timer 3 (16-bit)"]
pub type Gpt163 = crate::Periph<gpt162::RegisterBlock, 0x4007_8300>;
impl core::fmt::Debug for Gpt163 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpt163").finish()
    }
}
#[doc = "General PWM Timer 3 (16-bit)"]
pub use self::gpt162 as gpt163;
#[doc = "General PWM Timer 4 (16-bit)"]
pub type Gpt164 = crate::Periph<gpt162::RegisterBlock, 0x4007_8400>;
impl core::fmt::Debug for Gpt164 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpt164").finish()
    }
}
#[doc = "General PWM Timer 4 (16-bit)"]
pub use self::gpt162 as gpt164;
#[doc = "General PWM Timer 5 (16-bit)"]
pub type Gpt165 = crate::Periph<gpt162::RegisterBlock, 0x4007_8500>;
impl core::fmt::Debug for Gpt165 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpt165").finish()
    }
}
#[doc = "General PWM Timer 5 (16-bit)"]
pub use self::gpt162 as gpt165;
#[doc = "General PWM Timer 6 (16-bit)"]
pub type Gpt166 = crate::Periph<gpt162::RegisterBlock, 0x4007_8600>;
impl core::fmt::Debug for Gpt166 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpt166").finish()
    }
}
#[doc = "General PWM Timer 6 (16-bit)"]
pub use self::gpt162 as gpt166;
#[doc = "General PWM Timer 7 (16-bit)"]
pub type Gpt167 = crate::Periph<gpt162::RegisterBlock, 0x4007_8700>;
impl core::fmt::Debug for Gpt167 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpt167").finish()
    }
}
#[doc = "General PWM Timer 7 (16-bit)"]
pub use self::gpt162 as gpt167;
#[doc = "Output Phase Switching Controller"]
pub type GptOps = crate::Periph<gpt_ops::RegisterBlock, 0x4007_8ff0>;
impl core::fmt::Debug for GptOps {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GptOps").finish()
    }
}
#[doc = "Output Phase Switching Controller"]
pub mod gpt_ops;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "SYSTEM"]
    pub system: System,
    #[doc = "BUS"]
    pub bus: Bus,
    #[doc = "CAC"]
    pub cac: Cac,
    #[doc = "CAN0"]
    pub can0: Can0,
    #[doc = "DBG"]
    pub dbg: Dbg,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "CTSU"]
    pub ctsu: Ctsu,
    #[doc = "DAC12"]
    pub dac12: Dac12,
    #[doc = "DAC8"]
    pub dac8: Dac8,
    #[doc = "DMAC0"]
    pub dmac0: Dmac0,
    #[doc = "DMAC1"]
    pub dmac1: Dmac1,
    #[doc = "DMAC2"]
    pub dmac2: Dmac2,
    #[doc = "DMAC3"]
    pub dmac3: Dmac3,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "DOC"]
    pub doc: Doc,
    #[doc = "DTC"]
    pub dtc: Dtc,
    #[doc = "ELC"]
    pub elc: Elc,
    #[doc = "FCACHE"]
    pub fcache: Fcache,
    #[doc = "PORT0"]
    pub port0: Port0,
    #[doc = "PORT1"]
    pub port1: Port1,
    #[doc = "PORT2"]
    pub port2: Port2,
    #[doc = "PORT3"]
    pub port3: Port3,
    #[doc = "PORT4"]
    pub port4: Port4,
    #[doc = "PORT5"]
    pub port5: Port5,
    #[doc = "PORT6"]
    pub port6: Port6,
    #[doc = "PORT7"]
    pub port7: Port7,
    #[doc = "PORT8"]
    pub port8: Port8,
    #[doc = "PORT9"]
    pub port9: Port9,
    #[doc = "PFS"]
    pub pfs: Pfs,
    #[doc = "PMISC"]
    pub pmisc: Pmisc,
    #[doc = "ICU"]
    pub icu: Icu,
    #[doc = "IIC0"]
    pub iic0: Iic0,
    #[doc = "IIC1"]
    pub iic1: Iic1,
    #[doc = "IWDT"]
    pub iwdt: Iwdt,
    #[doc = "KINT"]
    pub kint: Kint,
    #[doc = "MSTP"]
    pub mstp: Mstp,
    #[doc = "MMPU"]
    pub mmpu: Mmpu,
    #[doc = "SMPU"]
    pub smpu: Smpu,
    #[doc = "SPMON"]
    pub spmon: Spmon,
    #[doc = "OPAMP"]
    pub opamp: Opamp,
    #[doc = "POEG"]
    pub poeg: Poeg,
    #[doc = "SRAM"]
    pub sram: Sram,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SCI0"]
    pub sci0: Sci0,
    #[doc = "SCI1"]
    pub sci1: Sci1,
    #[doc = "SCI2"]
    pub sci2: Sci2,
    #[doc = "SCI9"]
    pub sci9: Sci9,
    #[doc = "SLCDC"]
    pub slcdc: Slcdc,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "SSIE0"]
    pub ssie0: Ssie0,
    #[doc = "TSN"]
    pub tsn: Tsn,
    #[doc = "USBFS"]
    pub usbfs: Usbfs,
    #[doc = "WDT"]
    pub wdt: Wdt,
    #[doc = "ACMPLP"]
    pub acmplp: Acmplp,
    #[doc = "ADC140"]
    pub adc140: Adc140,
    #[doc = "AGT0"]
    pub agt0: Agt0,
    #[doc = "AGT1"]
    pub agt1: Agt1,
    #[doc = "GPT320"]
    pub gpt320: Gpt320,
    #[doc = "GPT321"]
    pub gpt321: Gpt321,
    #[doc = "GPT162"]
    pub gpt162: Gpt162,
    #[doc = "GPT163"]
    pub gpt163: Gpt163,
    #[doc = "GPT164"]
    pub gpt164: Gpt164,
    #[doc = "GPT165"]
    pub gpt165: Gpt165,
    #[doc = "GPT166"]
    pub gpt166: Gpt166,
    #[doc = "GPT167"]
    pub gpt167: Gpt167,
    #[doc = "GPT_OPS"]
    pub gpt_ops: GptOps,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            system: System::steal(),
            bus: Bus::steal(),
            cac: Cac::steal(),
            can0: Can0::steal(),
            dbg: Dbg::steal(),
            crc: Crc::steal(),
            ctsu: Ctsu::steal(),
            dac12: Dac12::steal(),
            dac8: Dac8::steal(),
            dmac0: Dmac0::steal(),
            dmac1: Dmac1::steal(),
            dmac2: Dmac2::steal(),
            dmac3: Dmac3::steal(),
            dma: Dma::steal(),
            doc: Doc::steal(),
            dtc: Dtc::steal(),
            elc: Elc::steal(),
            fcache: Fcache::steal(),
            port0: Port0::steal(),
            port1: Port1::steal(),
            port2: Port2::steal(),
            port3: Port3::steal(),
            port4: Port4::steal(),
            port5: Port5::steal(),
            port6: Port6::steal(),
            port7: Port7::steal(),
            port8: Port8::steal(),
            port9: Port9::steal(),
            pfs: Pfs::steal(),
            pmisc: Pmisc::steal(),
            icu: Icu::steal(),
            iic0: Iic0::steal(),
            iic1: Iic1::steal(),
            iwdt: Iwdt::steal(),
            kint: Kint::steal(),
            mstp: Mstp::steal(),
            mmpu: Mmpu::steal(),
            smpu: Smpu::steal(),
            spmon: Spmon::steal(),
            opamp: Opamp::steal(),
            poeg: Poeg::steal(),
            sram: Sram::steal(),
            rtc: Rtc::steal(),
            sci0: Sci0::steal(),
            sci1: Sci1::steal(),
            sci2: Sci2::steal(),
            sci9: Sci9::steal(),
            slcdc: Slcdc::steal(),
            spi0: Spi0::steal(),
            spi1: Spi1::steal(),
            ssie0: Ssie0::steal(),
            tsn: Tsn::steal(),
            usbfs: Usbfs::steal(),
            wdt: Wdt::steal(),
            acmplp: Acmplp::steal(),
            adc140: Adc140::steal(),
            agt0: Agt0::steal(),
            agt1: Agt1::steal(),
            gpt320: Gpt320::steal(),
            gpt321: Gpt321::steal(),
            gpt162: Gpt162::steal(),
            gpt163: Gpt163::steal(),
            gpt164: Gpt164::steal(),
            gpt165: Gpt165::steal(),
            gpt166: Gpt166::steal(),
            gpt167: Gpt167::steal(),
            gpt_ops: GptOps::steal(),
        }
    }
}
